import {
  AMEX_CARD_NUMBER_LENGTH_BY_POSITION,
  DINERS_CARD_NUMBER_LENGTH_BY_POSITION,
  MASTER_CARD_NUMBER_LENGTH_BY_POSITION,
  UNIONPAY_CARD_NUMBER_LENGTH_BY_POSITION,
  VISA_CARD_NUMBER_LENGTH_BY_POSITION,
} from '../constants/cardNumberlengthByPosition';
import { CardNetWork } from '../useCardNumbers/useCardNumbers';

const CARD_NUMBER_LENGTH_BY_POSITION_MAP: Record<
  CardNetWork,
  Record<string, number>
> = {
  VISA: VISA_CARD_NUMBER_LENGTH_BY_POSITION,
  MASTER: MASTER_CARD_NUMBER_LENGTH_BY_POSITION,
  AMEX: AMEX_CARD_NUMBER_LENGTH_BY_POSITION,
  DINERS: DINERS_CARD_NUMBER_LENGTH_BY_POSITION,
  UNIONPAY: UNIONPAY_CARD_NUMBER_LENGTH_BY_POSITION,
};

export default CARD_NUMBER_LENGTH_BY_POSITION_MAP;
