# Workflow name
name: 'React Payments Module Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: yarn
        working-directory: components

      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        working-directory: components
